### **01.1 create a dataframe views with two columns: datetime and user by reading feed-views.log**

In [1]:
import pandas as pd
df = pd.read_csv("../../datasets/feed-views-semicolon.log", index_col=None, delimiter=';')
# convert the datetime to the datetime64[ns] Dtype
df.date_time = pd.to_datetime(df.date_time)
# extract the year, month, day, hour, minute, and second from the values of that column to the new columns
df['year'] = df.date_time.dt.year
df['month'] = df.date_time.dt.month
df['day'] = df.date_time.dt.day
df['hour'] = df.date_time.dt.hour
df['minute'] = df.date_time.dt.minute
df['second'] = df.date_time.dt.second
df

,date_time,user,year,month,day,hour,minute,second
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23
2,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52
3,2020-04-17 12:36:21.401412,oksana,2020,4,17,12,36,21
4,2020-04-17 12:36:22.023355,oksana,2020,4,17,12,36,22
...,...,...,...,...,...,...,...,...
1067,2020-05-21 16:36:40.915488,ekaterina,2020,5,21,16,36,40
1068,2020-05-21 17:49:36.429237,maxim,2020,5,21,17,49,36
1069,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20
1070,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6
1071,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49

### **01.2 create the new column daytime**

In [2]:
# you need to assign the particular time of day value if an hour is within a particular interval, 
# for example, afternoon if the hour is larger than 11 and less or equal to 17
# 0 – 3.59 night, 4 – 6.59 early morning, 7 – 10.59 morning, 11 – 16.59 afternoon, 17 – 19.59 early evening, 20 – 23.59 evening
# use the method cut to solve this subtask
bins = [-1, 3, 6, 10, 16, 19, 24]
# means (-1,3], (3,6], (3,4] ...
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']
df['daytime'] = pd.cut(df.hour, bins=bins, labels=labels)
# assign the column user as the index
df.set_index('user', inplace=True)
df

,date_time,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
oksana,2020-04-17 12:36:21.401412,2020,4,17,12,36,21,afternoon
oksana,2020-04-17 12:36:22.023355,2020,4,17,12,36,22,afternoon
...,...,...,...,...,...,...,...,...
ekaterina,2020-05-21 16:36:40.915488,2020,5,21,16,36,40,afternoon
maxim,2020-05-21 17:49:36.429237,2020,5,21,17,49,36,early evening
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,evening

### **01.3 calculate the number of elements in your dataframe**

In [3]:
# use the method count()
df.count()
# 4 missing because of ex00.read_csv:
# filter the rows with index 2 and 3 using the argument skiprows, we know that these observations were fake
# filter the last 2 rows from the footer using the argument skipfooter, we know that these observations were fake too

date_time    1072
year         1072
month        1072
day          1072
hour         1072
minute       1072
second       1072
daytime      1072
dtype: int64

In [4]:
# calculate the number of elements in each time of day category using the method
df.daytime.value_counts()

daytime
evening          508
afternoon        250
early evening    145
night            129
morning           35
early morning      5
Name: count, dtype: int64

### **01.4 sort values in your dataframe by hour, minute, and second in ascending order (simultaneously and not one by one)**

In [5]:
df.sort_values(by=['hour', 'minute', 'second'])
df

,date_time,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
oksana,2020-04-17 12:36:21.401412,2020,4,17,12,36,21,afternoon
oksana,2020-04-17 12:36:22.023355,2020,4,17,12,36,22,afternoon
...,...,...,...,...,...,...,...,...
ekaterina,2020-05-21 16:36:40.915488,2020,5,21,16,36,40,afternoon
maxim,2020-05-21 17:49:36.429237,2020,5,21,17,49,36,early evening
valentina,2020-05-21 18:45:20.441142,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06.457819,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:49.995349,2020,5,21,23,23,49,evening

### **01.5 calculate the minimum and maximum for the hours and the mode for the daytime categories**

In [6]:
# calculate the maximum of hour for the rows where the time of day is night
df.loc[df.daytime == 'night'].hour.max()

np.int32(3)

In [7]:
## In addition to this, find out who visited the page at those hours
df.loc[df.hour == df.loc[df.daytime == 'night'].hour.max()]

,date_time,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night
konstantin,2020-04-19 03:23:55.473926,2020,4,19,3,23,55,night
konstantin,2020-04-19 03:33:07.757714,2020,4,19,3,33,7,night

In [8]:
# calculate the minimum of hour for the rows where the time of day is morning
df.loc[df.daytime == 'morning'].hour.min()

np.int32(8)

In [9]:
## In addition to this, find out who visited the page at those hours
df.loc[df.hour == df.loc[df.daytime == 'morning'].hour.min()]

,date_time,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning

In [10]:
# calculate the mode for the hour and daytime
df.hour.mode()

0    22
Name: hour, dtype: int32

In [11]:
df.daytime.mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

### **01.6 show the 3 earliest hours in the morning and the corresponding usernames and the 3 latest hours and the usernames using nsmallest() and nlargest()**

In [12]:
df.loc[df.daytime == 'morning'].nsmallest(3, 'hour')

,date_time,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning
artem,2020-04-24 09:42:47.598208,2020,4,24,9,42,47,morning

In [13]:
df.loc[df.daytime == 'morning'].nlargest(3, 'hour')

,date_time,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-18 10:53:52.623447,2020,4,18,10,53,52,morning
maxim,2020-04-18 10:56:55.833899,2020,4,18,10,56,55,morning
konstantin,2020-04-18 10:57:37.331258,2020,4,18,10,57,37,morning

### **01.7 use the method describe() to get the basic statistics for the columns**

In [14]:
# to find out what the most popular interval for visiting the page is, calculate the interquartile range for the hour by
df.describe()

,date_time,year,month,day,hour,minute,second
count,1072,1072.0,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000
mean,2020-05-10 09:30:16.241518592,2020.0,4.872201,13.531716,16.256530,29.602612,29.508396
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:53.448644096,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:30:41.062071296,2020.0,5.000000,14.000000,22.000000,46.000000,45.000000
max,2020-05-21 23:23:49.995349,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.334021,4.901354,6.960369,17.710471,17.424398

In [15]:
iqr = df.hour.quantile(.75) - df.hour.quantile(.25)
iqr

np.float64(9.0)