###  **00.1 Load and save**

In [1]:
import pandas as pd

df = pd.read_csv("../../datasets/feed-views.log", skiprows=[2,3], skipfooter=2, delimiter='\t', engine='python', header=None)
df.columns = ['datetime', 'user']
df.set_index('datetime', inplace=True)

In [2]:
df.head()

                              user
datetime
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [3]:
df.tail()

                                 user
datetime
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

In [4]:
df.index.names=['date_time']
df.to_csv("../../datasets/feed-views-semicolon.log", sep=';')

In [5]:
df.count()

user    1072
dtype: int64